#!/bin/sh

### BEGIN INIT INFO
# Provides:          quotarpc
# Short-Description: Starts rpc process for remote quota handling
# Required-Start:    $local_fs $remote_fs $portmap quota
# Required-Stop:     $local_fs $remote_fs $portmap quota
# Default-Start:     S 2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=rpc.rquotad
DESC="quota service"

# names of binaries
DAEMON=/usr/sbin/rpc.rquotad

# check if quota are enabled
if test -f /etc/exports && grep -q '^[^#]*quota' /etc/fstab && grep -q '^/' /etc/exports; then
        need_rquotad=1
else
        need_rquotad=0
fi

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

# check if there are some options to rpc.rquotad
test -f /etc/default/quota || exit 0
. /etc/default/quota

set -e

case "$1" in
  start)
	# The daemon
	if [ -x $DAEMON ] && [ $need_rquotad = 1 ]; then
	   log_daemon_msg "Starting $DESC" "rpc.rquotad"
	   start-stop-daemon --start --quiet --exec $DAEMON -- $RPCRQUOTADOPTS
	   log_end_msg $?
	fi	
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "rpc.rquotad"
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	log_end_msg $?
	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
