---
abstract: 'Remove files and directories'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::Remove
name: File-Remove
no_index:
  directory:
    - inc
    - t
requires:
  File::Copy: 0
  File::Glob: 0
  File::Path: 0
  File::Spec: 0.80
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.42
