#!/usr/bin/perl -w
#
# source:
#   /var/cvs/projects/debian/dpkg.common/get_option_tmpdir,v
#
# revision:
#   @(#) get_option_tmpdir,v 1.2 1999/03/08 04:34:57 jplejacq Exp
#
# copyright:
#   Copyright (C) 1999 Jean Pierre LeJacq <jplejacq@quoininc.com>
#
#   Distributed under the GNU GENERAL PUBLIC LICENSE.
#
# synopsis:
#   get_option_tmpdir -P <DH_TMPDIR> ...
#
# description:
#   Return the option <DH_TMPDIR> using debhelper library.
#
#   This program is package independent and should work unmodified
#   with any package.
#
#   This uses debhelper to ensure compatiblity.
#
# bugs:
#   No error handling.
#
#   This should be part of dpkg or debhelper.
#
#   This should be modeled after dpkg-parsechangelog.


# main:

# NMU
#  BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
#  use Dh_Lib;
  BEGIN { push @INC, "debian" }
  use Debian::Debhelper::Dh_Lib;
  init();

  my @result=$dh{TMPDIR};
  print "@result";
