.\" -*- nroff -*-
.TH mkpv 8
.SH NAME
mkpv \- creates PV
.SH SYNOPSIS
\fBmkpv\fR [--configfile] [--version] [--force]
	     [--upgrade] [-acvfuv] </dev/md?>+


.SH DESCRIPTION
\fBmkpv\fR sets up a block devices into a single PV.

Note that initializing PV devices \fBdestroys all of the data on
the consituent devices\fR. 

.SH OPTIONS
.IP "\fB-c\fP, \fB\-\-configfile\fP \fIfilename\fR"
Use \fIfilename\fR as the configuration file (\fB/etc/raidtab\fR is used
by default).

.IP "\fB\-f\fP, \fB\-\-force\fP"
Initilize the consituent devices, even if they appear to have data on
them already.

.IP "\fB\-h\fP, \fB\-\-help\fP"
Displays a short usage message, then exits.

.IP "\fB\-V\fP, \fB\-\-version\fP"
Displays a short version message, then exits.

.SH NOTES

The raidtools are derived from the md-tools and raidtools packages, which
were originally written by Marc Zyngier, Miguel de Icaza, Gadi Oxman, 
Bradley Ward Allen, and Ingo Molnar.

.SH AUTHOR
Ingo Molnar

.SH BUGS
Probably many.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8)
