.\" -*- nroff -*-
.TH raidadd 8
.SH NAME
raidadd, \- obsolete RAID command
.SH SYNOPSIS
.BI raidadd

in earlier RAID versions, \fBraidadd\fR was a utility used to start
up a RAID array. This work is now done by the kernel for 'persistent'
RAID arrays, or by mkraid/raid0run for (old) nonpersistent arrays.
If kernel autostart is disabled for an array then the 'raidstart'
command can be used.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8),
.IR raid0run (8),
.IR mkraid (8),
.IR raidstop (8)
