.\" -*- nroff -*-
.TH raidrun 8
.SH NAME
raidrun, \- obsolete RAID command
.SH SYNOPSIS
.BI raidrun

in earlier RAID versions, \fBraidrun\fR was a utility used to start
up a RAID array. This work is now done by the kernel for 'persistent'
RAID arrays, or by mkraid/raid0run for (old) nonpersistent arrays.
If kernel autostart is disabled for an array then the 'raidstart'
command can be used.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8)
