.\" -*- nroff -*-
.TH raid0run 8
.SH NAME
raid0run \- starts up old (superblock-less) RAID0/LINEAR arrays
.SH SYNOPSIS
\fBraid0run\fR [--configfile] [--version] [--force]
	     [--upgrade] [-acvfuv] </dev/md?>+


.SH DESCRIPTION
\fBraid0run\fR sets up a set of block devices into a single RAID0 array.
It looks in its configuration file for the md devices mentioned on the
command line, and initializes those arrays.  \fBraid0run\fR only works
for RAID0 and LINEAR devices, it's ment as a compatibility/migration
command for arrays created with old mdtools.

Note that initializing RAID devices with the wrong RAID configuration
file might destroy all data on the consituent devices! RAID arrays with
superblocks are much safer and are auto-started by the kernel.\fR. 

.SH OPTIONS
.IP "\fB-c\fP, \fB\-\-configfile\fP \fIfilename\fR"
Use \fIfilename\fR as the configuration file (\fB/etc/raidtab\fR is used
by default).

.IP "\fB\-a\fP, \fB\-\-all\fP"
Starts up all nonpersistent RAID0 and LINEAR arrays defined in raidtab.
It skips all persistent or non-RAID0/LINEAR arrays. This switch is handy
to be used in startup scripts for old installations.

.IP "\fB\-h\fP, \fB\-\-help\fP"
Displays a short usage message, then exits.

.IP "\fB\-V\fP, \fB\-\-version\fP"
Displays a short version message, then exits.

.SH NOTES

The raidtools are derived from the md-tools and raidtools packages, which
were originally written by Marc Zyngier, Miguel de Icaza, Gadi Oxman, 
Bradley Ward Allen, and Ingo Molnar.

.SH BUGS
no known bugs.

.SH SEE ALSO
.IR raidtab (5)
