.\" -*- nroff -*-
.TH raidstart 8
.SH NAME
raidstart, raidstop, \- command set to manage md devices.
.SH SYNOPSIS

.BI raidstart
[options] <raiddevice>*

.BI raidstop
[options] <raiddevice>

.SH DESCRIPTION
RAID devices are virtual devices created from two or more real block
devices. This allows multiple disks to be combined into a single
filesystem, possibly with automated backup and recovery. Linux RAID
devices are implemented through the md device driver.

If you're using the
.B /proc
filesystem,
.B /proc/mdstat
gives you informations about md devices status.

Currently, Linux supports linear md devices, RAID0 (striping), 
RAID1 (mirrroring), and RAID4 and RAID5. For information on
the various levels of RAID, check out:

     http://ostenfeld.dk/~jakob/Software-RAID.HOWTO/

And for instruction for upgrading from a regular system to software raid:

     http://www.tldp.org/HOWTO/Boot+Root+Raid+LILO.html

For new releases of the RAID driver check out:

     ftp://ftp.fi.kernel.org/pub/linux/daemons/raid/alpha

Avaible commands are :

.br
.B mkraid
: configures (creates) md (RAID) devices in the kernel, banding multiple devices into one.
.br

.B raidstart
: activates (starts) an existing 'persistent' md device
.br

.B raid0run
: activates old nonpersistent RAID0/LINEAR md devices
.br

.B raidstop
: turns off an md device, and unconfigures (stops) it
.br

By default, a systems RAID configuration is kept in \fB/etc/raidtab\fR, which
can configure multiple RAID devices. 

All of these tools work similiarly. If \fB-a\fR (or \fB-\-all\fR) is
specified, the specified operation is performed on all of the RAID
devices mentioned in the configuration file. Otherwise, one or more
RAID devices must be specified on the command line. For example:

.B raid0run -a

Starts all of the 'old' RAID0 RAID devices specified in \fB/etc/raidtab\fR. If
only \fI/dev/md1\fR should be started, the following command
should be used instead:

.B raidstart /dev/md1


.SH OPTIONS
.IP "\fB\-a\fP, \fB\-\-all\fP"
Apply the command to all of the configurations specified in the config file.

.IP "\fB-c\fP, \fB\-\-configfile\fP \fIfilename\fR"
Use \fIfilename\fR as the configuration file (\fB/etc/raidtab\fR is used
by default).

.IP "\fB\-h\fP, \fB\-\-help\fP"
Displays a short usage message, then exits.

.IP "\fB\-V\fP, \fB\-\-version\fP"
Displays a short version message, then exits.

.SH NOTES

The raidtools are derived from the md-tools and raidtools packages, which
were originally written by Marc Zyngier, Miguel de Icaza, Gadi Oxman, 
Bradley Ward Allen, and Ingo Molnar.

.SH BUGS
no known bugs.

.SH SEE ALSO
.IR raidtab (5),
.IR raid0run (8),
.IR raidstop (8),
.IR mkraid (8)
