#!/bin/sh
# autopkgtest check: Run the installed-tests to verify glib works correctly
# (C) 2013 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>

set -e

export XDG_RUNTIME_DIR=$ADTTMP

env -u http_proxy dbus-run-session -- xvfb-run -a gnome-desktop-testing-runner glib-networking
