.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CGICC-CONFIG 1 "11 September 07"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cgicc-config \- script to get information about the installed version of cgicc
.SH SYNOPSIS
.B cgicc-config
[\-\-prefix] [\-\-exec\-prefix] [\-\-version] [\-\-libs] [\-\-static-libs] [\-\-cflags]
.SH DESCRIPTION
.B cgicc-config
displays information about the libcgicc installation
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-\-prefix
Display architecture-independent installation dir
.TP
.B \-\-exec\-prefix
Display architecture-dependent installation dir
.TP
.B \-\-includedir
Display header file installation dir
.TP
.B \-\-libdir
Display object-code installation dir
.TP
.B \-\-host
Display host information
.TP
.B \-\-version
Display version information
.TP
.B \-\-help
Display summary of options.
.SH AUTHOR
This manual page was written by Chris Butler <chrisb@debian.org>,
for the Debian project (but may be used by others).
