.TH NTP 1 
.SH NAME
ntp \- the network time protocol
.SH "DESCRIPTION"
The NTP distribution does not include man pages, but it does include a
thorough manual in HTML.  To help Debian users manage disk space, this 
documentation is packaged separately from the executables. 
.PP
To learn more
about the NTP protocol and this software, please install the ntp-doc package
and then look in /usr/share/doc/ntp-doc where you will find an html 
documentation tree.
.SH AUTHOR
This manual page was written by Bdale Garbee <bdale@gag.com>
for the Debian GNU/Linux system (but may be used by others).
