#! /bin/sh

if [ -x /etc/init.d/atd ]
then
	/etc/init.d/atd stop
fi
# Remove FSSTND compatibility symlink from obsolete /usr/doc
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/at ] ; then
    rm -f /usr/doc/at
fi
