#! /bin/sh -e


if [ "$1" = "configure" ]; then
    if [ -d /usr/doc -a ! -e /usr/doc/mime-support -a -d /usr/share/doc/mime-support ]; then
	ln -sf ../share/doc/mime-support /usr/doc/mime-support
    fi
fi


# Remove the old status directory (and any orphaned install-mime program)
rm -fr /var/lib/mime
rm -f  /usr/sbin/install-mime


# Run the update program
if [ -x /usr/sbin/update-mime ]; then
    update-mime
fi
