#! /bin/sh

set -e

old_docdirs()
{
	# For some reason the old libltdl3-dev document directories don't
	# get removed which means we'll error when we try to make our symlink.
	# Get rid of them.
	rm -rf /usr/share/doc/libltdl0-dev
	rm -rf /usr/share/doc/libltdl3-dev
}

case "$1" in
install)
	;;

upgrade)
	old_docdirs
	;;

abort-upgrade)
	;;

*)
	echo "preinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
