#!/bin/sh
#
# source:
#   /var/cvs/projects/debian/cracklib/debian/dpkg.scripts/build,v
#
# revision:
#   @(#) build,v 1.1 1999/03/29 15:14:54 jplejacq Exp
#
# copyright:
#   Copyright (C) 1998, 1999 Jean Pierre LeJacq <jplejacq@quoininc.com>
#
#   Distributed under the GNU GENERAL PUBLIC LICENSE.
#
# synopsis:
#   . build
#
# description:
#   Build function for package.
#
#   This function is package dependent.


build_override()
# postconditions:
#   Return 0 if successful, exits with non-zero otherwise.
#
# description:
#   Build package.
{
  echo "${0}: building for selected package..."
    if   [ "${pkg}" = "${DH_DOPACKAGES}" ]
    then
      readonly rules_srcdir="${pkg}.src/cracklib"
      cd ${rules_srcdir} && make libcrack.so.${ver}
    elif [ "${pkg}-dev" = "${DH_DOPACKAGES}" ]
    then
      readonly rules_srcdir="cracklib2-dev.src/cracklib"
      cd ${rules_srcdir} && make libcrack.a
    elif [ "${pkgbase}-runtime" = "${DH_DOPACKAGES}" ]
    then
      readonly rules_srcdir="${pkgbase}-runtime.src/util"
      cd ${rules_srcdir} && make all
    else
      echo "${0}: unknown package..."
      exit 1
    fi


  return 0
}
