#!/bin/sh
#
# source:
#   /var/cvs/projects/debian/cracklib/debian/dpkg.scripts/substfiles,v
#
# revision:
#   @(#) substfiles,v 1.11 1999/04/02 14:48:53 jplejacq Exp
#
# copyright:
#   Copyright (C) 1998, 1999 Jean Pierre LeJacq <jplejacq@quoininc.com>
#
#   Distributed under the GNU GENERAL PUBLIC LICENSE.
#
# description:
#   Define file system structure for package.
#
#   The idea behind this file is to support a variety of directory
#   layouts.  Two layouts are supported here: standard and opt.  Each
#   layout defines the directories that the files are installed in and
#   links that may be reguired to these files from standard locations
#   in the debian file system.
#
#   In addition, this file may define several binary packages from the
#   single source package.  All must be defined simulataneously since
#   they may depend on one another.  Consequently, the file is
#   organized as:
#
#     file_structure_0
#       binary_package_0
#       binary_package_1
#       ...
#     file_structure_1
#       binary_package_0
#       binary_package_1
#       ...
#     ...
#
#   This file is dependent on debian/dpkg.common/substfiles which
#   defines the standard host directories and files as well as the
#   source package name and version.
#
#   This is not a complete shell script.  Must be included in another
#   file.


# main:
  # debian binary packages:
    #
    # This is required since the library name uses the standard of
    # including the major version number but the supporting run-time
    # and development packages do not.
    #
    readonly pkgbase="cracklib"

    readonly pkglib="${pkg}"
    readonly pkgdev="${pkg}-dev"
    readonly pkgruntime="${pkgbase}-runtime"


  # source:
    f_pkg_src="${pkgbase},${ver}.tgz"
 
    url_pkg_dir="http://www.users.dircon.co.uk/~crypto"
    url_pkg_src="${url_pkg_dir}/${f_pkg_src}"

    d_pkg_src_unpacked="${pkgbase},${ver}"


  if [ -f "scheme-opt" ]
  then
    # pkg binary package:
      d_pkglib_root="${d_host_opt}/${pkg}"

      # directories:
        d_pkglib_doc="${d_pkglib_root}/doc"
        d_pkglib_docbase="${d_pkglib_doc}"
        d_pkglib_lib="${d_pkglib_root}/lib"


      # files:
        f_pkglib_docbase="${d_pkglib_docbase}/${pkglib}.doc-base"


      # links:
        l_pkglib_doc="${d_host_doc}/${pkglib}"
        l_pkglib_docbase="${d_host_docbase}/${pkglib}"


    # pkgdev binary package:
      d_pkgdev_root="${d_host_opt}/${pkgdev}"

      # directories:
        d_pkgdev_doc="${d_pkgdev_root}/doc"
        d_pkgdev_doc_examples="${d_pkgdev_doc}/examples"
        d_pkgdev_docbase="${d_pkgdev_doc}"
        d_pkgdev_include="${d_pkgdev_root}/include"
        d_pkgdev_lib="${d_pkgdev_root}/lib"
        d_pkgdev_man="${d_pkgdev_root}/man"


      # files:
        f_pkgdev_docbase="${d_pkgdev_docbase}/${pkgdev}.doc-base"


      # links:
        l_pkgdev_doc="${d_host_doc}/${pkgdev}"
        l_pkgdev_docbase="${d_host_docbase}/${pkgdev}"

        l_pkgdev_pkglib_relative_lib="../../${pkglib}/lib/"


    # pkgruntime:
      d_pkgruntime_root="${d_host_opt}/${pkgruntime}"

      # directories:
        d_pkgruntime_bin_s="${d_pkgruntime_root}/sbin"
        d_pkgruntime_doc="${d_pkgruntime_root}/doc"
        d_pkgruntime_docbase="${d_pkgruntime_doc}"
        d_pkgruntime_etc="${d_host_opt_etc}/${pkgbase}"
        d_pkgruntime_man="${d_pkgruntime_root}/man"

        d_pkgruntime_cache="${d_host_cache}/${pkgbase}"


      # files:
        f_pkgruntime_docbase="${d_pkgruntime_docbase}/${pkgruntime}.doc-base"
        f_pkgruntime_etc_conf="${d_pkgruntime_etc}/${pkgbase}.conf"
        f_pkgruntime_etc_crondaily="${d_pkgruntime_etc}/${pkgbase}.cron-daily"

        f_pkgruntime_dict_db_prefix="cracklib_dict"
        f_pkgruntime_dict_db="${d_pkgruntime_cache}/${f_pkgruntime_dict_db_prefix}"


      # links:
        l_pkgruntime_doc="${d_host_doc}/${pkgruntime}"
        l_pkgruntime_docbase="${d_host_docbase}/${pkgruntime}"
        l_pkgruntime_etc_crondaily="${d_host_etc_crondaily}/${pkgbase}"
  else
    # pkglib binary package:
      # directories:
        d_pkglib_doc="${d_host_doc}/${pkglib}"
        d_pkglib_docbase="${d_host_docbase}"
        d_pkglib_lib="${d_host_lib_usr}"


      # files:
        f_pkglib_docbase="${d_pkglib_docbase}/${pkglib}"


      # links:
        l_pkglib_doc="${d_pkglib_doc}"
        l_pkglib_docbase="${f_pkglib_docbase}"


    # pkgdev binary package:
      # directories:
        d_pkgdev_doc="${d_host_doc}/${pkgdev}"
        d_pkgdev_doc_examples="${d_pkgdev_doc}/examples"
        d_pkgdev_docbase="${d_host_docbase}"
        d_pkgdev_include="${d_host_include}"
        d_pkgdev_lib="${d_host_lib_usr}"
        d_pkgdev_man="${d_host_man}"


      # files:
        f_pkgdev_docbase="${d_pkgdev_docbase}/${pkgdev}"


      # links:
        l_pkgdev_doc="${d_pkgdev_doc}"
        l_pkgdev_docbase="${f_pkgdev_docbase}"

        l_pkgdev_pkglib_relative_lib=""


    # pkgruntime:
      # directories:
        d_pkgruntime_bin_s="${d_host_bin_s_usr}"
        d_pkgruntime_doc="${d_host_doc}/${pkgruntime}"
        d_pkgruntime_docbase="${d_host_docbase}"
        d_pkgruntime_etc="${d_host_etc}/${pkgbase}"
        d_pkgruntime_man="${d_host_man}"

        d_pkgruntime_cache="${d_host_cache}/${pkgbase}"


      # files:
        f_pkgruntime_docbase="${d_pkgruntime_docbase}/${pkgruntime}"
        f_pkgruntime_etc_conf="${d_pkgruntime_etc}/cracklib.conf"
        f_pkgruntime_etc_crondaily="${d_host_etc_crondaily}/${pkgbase}"

        f_pkgruntime_dict_db_prefix="cracklib_dict"
        f_pkgruntime_dict_db="${d_pkgruntime_cache}/${f_pkgruntime_dict_db_prefix}"


      # links:
        l_pkgruntime_doc="${d_pkgruntime_doc}"
        l_pkgruntime_docbase="${f_pkgruntime_docbase}"
        l_pkgruntime_etc_crondaily="${f_pkgruntime_etc_crondaily}"
  fi
