#!/bin/sh

# This scripts verifies that no name is present both in common and
# arch-specific configurations.

for archfile in modprobe.d/arch/*; do
	echo "Checking $archfile..."
	cat modprobe.d/aliases $archfile \
		| awk '/^[^#]/ {print $2}' | sort | uniq --repeated
done

