#!/bin/sh -e

[ "$1" -a -d "$1" ] || exit 1

for file in $(find $1/usr/share/man/ -type f); do
  perl -p \
    -e 's/(depmod|lsmod|modinfo|modprobe|rmmod|insmod).old/$1.modutils/g' \
    -i $file
done

