.TH UPDATE-MODULES 8 "17 June 2004" "Debian GNU/Linux" "Debian"
.SH NAME
update\-modules \- obsolete command
.SH SYNOPSIS
.B update\-modules
.SH DESCRIPTION
.B update\-modules
is an obsolete command. In its current form it will execute
.IR /sbin/update\-modules.modutils
(the old
.B update\-modules
program provided by the modutils package)
if it exists and do nothing else.
.PP
Note that the file 
.I /etc/modprobe.conf
is not the exact equivalent of 
\fI/etc/modules.conf\fR.
It is not required for module-init-tools and is not generated any more. In fact,
most people should not create that file since \fI/etc/modprobe.d/*\fR would be
ignored in this case but Debian packages store their additional configuration
files in \fI/etc/modprobe.d/\fR. 
.SH "SEE ALSO"
.BR depmod (1)
.BR modprobe (8)
.BR modprobe.conf (5)
.SH BUGS
This program should be removed after modutils will have been removed
from the distribution and no package will try to use it anymore.
.SH AUTHOR
This manual page was written by Marco d'Itri <\fImd@linux.it\fP>
for the Debian GNU/Linux system.
