#!/bin/sh

# Script to build links for all the exim source files from the system-
# specific build directory. It should be run from within that directory.

test ! -d ../src && \
  echo "*** $0 should be run in a system-specific subdirectory." && \
  exit 1
test -r version.c && \
  echo "*** It appears that $0 has already been run." && \
  exit 1

# Initialize the file holding the compile number

echo "0" > cnumber.h

echo ""
echo ">>> Creating links to source files..."

# The RFC1413 ident sources have to be linked independently
# in their own sub-directory, since their .o files are built
# using their own Makefile in the sub-directory.

mkdir libident
cd libident
ln -s ../../src/libident/Makefile        Makefile
ln -s ../../src/libident/INSTALL         INSTALL
ln -s ../../src/libident/README          README
ln -s ../../src/libident/id_close.c      id_close.c
ln -s ../../src/libident/id_open.c       id_open.c
ln -s ../../src/libident/id_parse.c      id_parse.c
ln -s ../../src/libident/id_query.c      id_query.c
ln -s ../../src/libident/ident-tester.c  ident-tester.c
ln -s ../../src/libident/ident.3         ident.3
ln -s ../../src/libident/ident.c         ident.c
ln -s ../../src/libident/ident.h         ident.h
ln -s ../../src/libident/lookup-tester.c lookup-tester.c
ln -s ../../src/libident/support.c       support.c
ln -s ../../src/libident/version.c       version.c
cd ..

# Likewise for the PCRE regular expression library
mkdir pcre
cd pcre
ln -s ../../src/pcre/Makefile            Makefile
ln -s ../../src/pcre/config.h            config.h
ln -s ../../src/pcre/dftables.c          dftables.c
ln -s ../../src/pcre/internal.h          internal.h
ln -s ../../src/pcre/pcre.h              pcre.h
ln -s ../../src/pcre/maketables.c        maketables.c
ln -s ../../src/pcre/get.c               get.c
ln -s ../../src/pcre/pcre.c              pcre.c
ln -s ../../src/pcre/pcretest.c          pcretest.c
ln -s ../../src/pcre/study.c             study.c
cd ..

# Likewise for the lookups
mkdir lookups
cd lookups
ln -s ../../src/lookups/README           README
ln -s ../../src/lookups/Makefile         Makefile
ln -s ../../src/lookups/cdb.h            cdb.h
ln -s ../../src/lookups/cdb.c            cdb.c
ln -s ../../src/lookups/dbmdb.h          dbmdb.h
ln -s ../../src/lookups/dbmdb.c          dbmdb.c
ln -s ../../src/lookups/dnsdb.h          dnsdb.h
ln -s ../../src/lookups/dnsdb.c          dnsdb.c
ln -s ../../src/lookups/ldap.h           ldap.h
ln -s ../../src/lookups/ldap.c           ldap.c
ln -s ../../src/lookups/lsearch.h        lsearch.h
ln -s ../../src/lookups/lsearch.c        lsearch.c
ln -s ../../src/lookups/mysql.h          mysql.h
ln -s ../../src/lookups/mysql.c          mysql.c
ln -s ../../src/lookups/nis.h            nis.h
ln -s ../../src/lookups/nis.c            nis.c
ln -s ../../src/lookups/nisplus.h        nisplus.h
ln -s ../../src/lookups/nisplus.c        nisplus.c
ln -s ../../src/lookups/pgsql.h          pgsql.h
ln -s ../../src/lookups/pgsql.c          pgsql.c
ln -s ../../src/lookups/testdb.h         testdb.h
ln -s ../../src/lookups/testdb.c         testdb.c
cd ..

# Likewise for the code for the directors
mkdir directors
cd directors
ln -s ../../src/directors/README         README
ln -s ../../src/directors/Makefile       Makefile
ln -s ../../src/directors/aliasfile.h    aliasfile.h
ln -s ../../src/directors/aliasfile.c    aliasfile.c
ln -s ../../src/directors/dfunctions.h   dfunctions.h
ln -s ../../src/directors/df_extracted.c df_extracted.c
ln -s ../../src/directors/df_generated.c df_generated.c
ln -s ../../src/directors/df_lookup.c    df_lookup.c
ln -s ../../src/directors/forwardfile.h  forwardfile.h
ln -s ../../src/directors/forwardfile.c  forwardfile.c
ln -s ../../src/directors/localuser.h    localuser.h
ln -s ../../src/directors/localuser.c    localuser.c
ln -s ../../src/directors/smartuser.h    smartuser.h
ln -s ../../src/directors/smartuser.c    smartuser.c
cd ..

# Likewise for the code for the routers
mkdir routers
cd routers
ln -s ../../src/routers/README           README
ln -s ../../src/routers/Makefile         Makefile
ln -s ../../src/routers/domainlist.h     domainlist.h
ln -s ../../src/routers/domainlist.c     domainlist.c
ln -s ../../src/routers/ipliteral.h      ipliteral.h
ln -s ../../src/routers/ipliteral.c      ipliteral.c
ln -s ../../src/routers/iplookup.h       iplookup.h
ln -s ../../src/routers/iplookup.c       iplookup.c
ln -s ../../src/routers/lookuphost.h     lookuphost.h
ln -s ../../src/routers/lookuphost.c     lookuphost.c
ln -s ../../src/routers/queryprogram.h   queryprogram.h
ln -s ../../src/routers/queryprogram.c   queryprogram.c
cd ..

# Likewise for the code for the transports
mkdir transports
cd transports
ln -s ../../src/transports/README        README
ln -s ../../src/transports/Makefile      Makefile
ln -s ../../src/transports/appendfile.h  appendfile.h
ln -s ../../src/transports/appendfile.c  appendfile.c
ln -s ../../src/transports/autoreply.h   autoreply.h
ln -s ../../src/transports/autoreply.c   autoreply.c
ln -s ../../src/transports/lmtp.h        lmtp.h
ln -s ../../src/transports/lmtp.c        lmtp.c
ln -s ../../src/transports/pipe.h        pipe.h
ln -s ../../src/transports/pipe.c        pipe.c
ln -s ../../src/transports/smtp.h        smtp.h
ln -s ../../src/transports/smtp.c        smtp.c
cd ..

# Likewise for the code for the authorization functions
mkdir auths
cd auths
ln -s ../../src/auths/README        README
ln -s ../../src/auths/Makefile      Makefile
ln -s ../../src/auths/b64encode.c   b64encode.c
ln -s ../../src/auths/b64decode.c   b64decode.c
ln -s ../../src/auths/call_pam.c    call_pam.c
ln -s ../../src/auths/get_data.c    get_data.c
ln -s ../../src/auths/md5.c         md5.c
ln -s ../../src/auths/xtextencode.c xtextencode.c
ln -s ../../src/auths/xtestdecode.c xtextdecode.c
ln -s ../../src/auths/cram_md5.c    cram_md5.c
ln -s ../../src/auths/cram_md5.h    cram_md5.h
ln -s ../../src/auths/plaintext.c   plaintext.c
ln -s ../../src/auths/plaintext.h   plaintext.h
cd ..

# The basic source files for Exim and utilities

ln -s ../src/dbfn.h            dbfn.h
ln -s ../src/exim.h            exim.h
ln -s ../src/functions.h       functions.h
ln -s ../src/globals.h         globals.h
ln -s ../src/macros.h          macros.h
ln -s ../src/structs.h         structs.h

ln -s ../src/accept.c          accept.c
ln -s ../src/buildconfig.c     buildconfig.c
ln -s ../src/child.c           child.c
ln -s ../src/daemon.c          daemon.c
ln -s ../src/dbfn.c            dbfn.c
ln -s ../src/debug.c           debug.c
ln -s ../src/deliver.c         deliver.c
ln -s ../src/direct.c          direct.c
ln -s ../src/directory.c       directory.c
ln -s ../src/dns.c             dns.c
ln -s ../src/drtables.c        drtables.c
ln -s ../src/dummies.c         dummies.c
ln -s ../src/exim.c            exim.c
ln -s ../src/exim_dbmbuild.c   exim_dbmbuild.c
ln -s ../src/exim_dumpdb.c     exim_dumpdb.c
ln -s ../src/exim_fixdb.c      exim_fixdb.c
ln -s ../src/exim_lock.c       exim_lock.c
ln -s ../src/exim_tidydb.c     exim_tidydb.c
ln -s ../src/expand.c          expand.c
ln -s ../src/filter.c          filter.c
ln -s ../src/globals.c         globals.c
ln -s ../src/header.c          header.c
ln -s ../src/host.c            host.c
ln -s ../src/log.c             log.c
ln -s ../src/match.c           match.c
ln -s ../src/moan.c            moan.c
ln -s ../src/parse.c           parse.c
ln -s ../src/perl.c            perl.c
ln -s ../src/queue.c           queue.c
ln -s ../src/readconf.c        readconf.c
ln -s ../src/retry.c           retry.c
ln -s ../src/rewrite.c         rewrite.c
ln -s ../src/route.c           route.c
ln -s ../src/search.c          search.c
ln -s ../src/smtp_in.c         smtp_in.c
ln -s ../src/smtp_out.c        smtp_out.c
ln -s ../src/spool_in.c        spool_in.c
ln -s ../src/spool_out.c       spool_out.c
ln -s ../src/store.c           store.c
ln -s ../src/string.c          string.c
ln -s ../src/tls.c             tls.c
ln -s ../src/tod.c             tod.c
ln -s ../src/transport.c       transport.c
ln -s ../src/tree.c            tree.c
ln -s ../src/verify.c          verify.c
ln -s ../src/version.c         version.c

# End of MakeLinks
