.TH RC.BOOT 5 "December 26, 1997" "" "Debian GNU/Linux Manual"
.SH NAME
/etc/rc.boot \- directory for local or per-package boot scripts.
.SH DESCRIPTION
The /etc/rc.boot directory is obsolete. It has been superseded by the
/etc/rcS.d directory. At boot time, first the /etc/rcS.d directory is scanned
and then, for backwards compatibility, the /etc/rc.boot directory.
.PP
The directory \fI/etc/rc.boot\fP is scanned by the program
\fBrun-parts\fP(8). The scripts found that have valid filenames for
the \fBrun-parts\fP program will be run in lexical sort order of the
filenames.
.SH "SEE ALSO"
run-parts(8), init(1).

