.TH rcS 5 "17 Nov 1999" "" "Debian Administrator's Manual"
.SH NAME
rcS -- defaults used at boot time
.SH DESCRIPTION
.I /etc/default/rcS
contains information in the following format:
.IP "" .5i
name=value
.PP
Only one value per line is allowed. Comments are allowed too and must start
with the ``#'' character.

.SH OPTIONS
The following options can be set, the defaults values are shown:

.IP \fBTMPTIME=0\fP
On bootup the files in /tmp will be cleaned up if their modification time
was more than TMPTIME days ago. A value of zero means that all files
are removed regardless of age. If you don't want the system to clean
/tmp set TMPTIME to a large value like 9125 (25 years).

.IP \fBSULOGIN=no\fB
Setting this to
.B yes
causes init to spawn a sulogin on the console as one of the first things
in the boot process. If the administrator does not login, the sulogin will
timeout after 30 seconds and the boot process will continue.

.IP \fBDELAYLOGIN=yes\fB
Normally the system will not let anyone login until the boot process
is complete and and the system has come up completely in the default runlevel
(usually level 2). However theoretically it's possible to login a bit earlier,
as soon as \fI/usr/sbin/inetd\fP is started. The default value of \fBno\fP
prevents this, setting it to \fByes\fP allows it.

.IP \fBUTC=\fP
This is used to interpret the system (BIOS) clock. If this option is set
to \fIno\fP the system clock is supposed to be set at local time. If this
option is set to \fIyes\fP the system clock is supposed to be set at UTC
(Universal Time, a.k.a. GMT).

.IP \fBVERBOSE=yes\fP
Setting this option to \fBno\fP will make the bootup a bit less verbose.

.IP \fBEDITMOTD=yes\fP
At boot time the system edits the first line of the file \fI/etc/motd\fP
and replaces it with the output from the command \fIuname -a\fP. Setting
this to \fBno\fP prohibits that.

.IP \fBFSCKFIX=no\fP
When the root and all other filesystems are checked, this happens with the
\fB-a\fP flag which means \fIautorepair\fP. If there are really big
inconsistencies, the fsck will bail out. The system will print a message
asking the administrator to repair the filesystem maually and present a
root shell prompt (actually a \fIsulogin\fP prompt) on the console. Setting
this option to \fB\fP yes causes the fsck commands to be run with the
\fB-y\fP option instead of the \fB-a\fP option. This will always repair
the filesystems without any interaction but might irreversibly damage
your file system(s).

.SH AUTHOR
Miquel van Smoorenburg <miquels@cistron.nl>
.SH SEE ALSO
init(8), inittab(5).
