.\" Copyright 2008,2009 Petter Reinholdtsen
.\" May be distributed under the GNU General Public License
.TH "update-bootsystem-insserv" "8" "28 July 2009" "Petter Reinholdtsen" ""
.SH "NAME"
update\-rc.d\-insserv \- obsolete
.SH "DESCRIPTION"
.B update\-rc.d\-insserv
is an obsolete implementation of the update-rc.d interface for the dependency
based boot sequencing system insserv.  The implementation was moved into the
sysv-rc update-rc.d implementation.
.SH "SEE ALSO"
update\-rc.d(8), insserv(8), update-bootsystem-insserv(8)
.SH "AUTHOR"
Petter Reinholdtsen, <pere@hungry.com>
