../../initramfs-tools/lvm2/* usr/share/initramfs-tools
etc/lvm/lvm.conf
lib/systemd/system/lvm2-activation*
lib/systemd/system/lvm2-lvmetad*
lib/systemd/system/lvm2-monitor*
lib/systemd/system/lvm2-pvscan*
lib/udev/rules.d/*-lvm*.rules
sbin/fsadm
sbin/lv*
sbin/pv*
sbin/vg*
usr/lib/tmpfiles.d/lvm2.conf
usr/share/man/man5/lvm*
usr/share/man/man7/lvm*
usr/share/man/man8/fsadm*
usr/share/man/man8/lv*
usr/share/man/man8/pv*
usr/share/man/man8/vg*
