--- #YAML:1.0
name:               DBD-mysql
version:            4.016
abstract:           A MySQL driver for the Perl5 Database Interface (DBI)
author:
    - Rudy Lippan <rlippan@remotelinux.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    DBI:           1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
