#! /bin/sh
#
#	Post removal script for the Debian GNU/Linux nis package
#

set -e

case "$1" in
	purge)
		update-rc.d nis remove >/dev/null
		exit 0
		;;
	remove)
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

exit 0
