#! /bin/sh

case "$1" in
  upgrade|remove)
	[ -L /usr/doc/nis ] && rm -f /usr/doc/nis
	;;
esac

set -e

case "$1" in
	remove|upgrade|remove-in-favour|deconfigure-in-favour)
		#
		#	Stop the daemons.
		#
		/etc/init.d/nis stop
		;;
	failed-upgrade)
		;;
	*)
		;;
esac

exit 0
