#! /bin/sh
#
# ypxfr_1perhour   Transfer the group and password files
#                  every hour in case we missed an update.
#                  (Or if we don't get automatic updates).
#
# Version:         @(#)ypxfr_1perhour.sh  1.01  MvS
#

MAPS="passwd.byname passwd.byuid shadow.byname group.byname group.bygid"

YPBINDIR=/usr/lib/yp

for map in $MAPS
do
  [ -t 1 ] && echo "$YPBINDIR/ypxfr $map"
  $YPBINDIR/ypxfr $map
done

