#! /bin/sh
#
# ypxfr_1perday    Transfer all NIS maps from the master
#                  in case we missed an update.
#                  (Or if we don't get automatic updates).
#
# Version:         @(#)ypxfr_1perday.sh  1.00  MvS
#

MAPS="protocols.byname protocols.bynumber rpc.bynumber services.byname"

YPBINDIR=/usr/lib/yp

for map in $MAPS
do
  [ -t 1 ] && echo "$YPBINDIR/ypxfr $map"
  $YPBINDIR/ypxfr $map
done

