#!/bin/sh
# Run upstream runtime tests
# Assumes $ADTTMP is set, see /usr/share/doc/autopkgtest/README.package-tests.gz
set -e

# We just copy and run the entire test suite to resp. from the $ADTTMP
# directory because it generates output within each test's source directory.
cp -r tests "$ADTTMP"
cd "$ADTTMP"/tests
make run
