#! /bin/sh

set -e

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/sysklogd ]
then
    rm -f /usr/doc/sysklogd
fi

if [ "$1" = "purge"  -o "$1" = "remove" ]
then
    sh /etc/init.d/sysklogd stop
fi

