.TH "apreq_value_t" 3 "8 Aug 2006" "Version 2.08" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apreq_value_t \- libapreq's pre-extensible string type  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <apreq.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBapr_size_t\fP \fBnlen\fP"
.br
.ti -1c
.RI "\fBapr_size_t\fP \fBdlen\fP"
.br
.ti -1c
.RI "char \fBdata\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
libapreq's pre-extensible string type 
.PP
\fBExamples: \fP
.in +1c
.PP
\fB/usr/home/pgollucci/dev/compile/freebsd-6.1-stable/3.4.4/apreq/429956/r428290/5.8.8-2.2.3-prefork/include/apreq.h\fP.
.PP
.SH "Field Documentation"
.PP 
.SS "char \fBapreq_value_t::data\fP[1]"
.PP
value data 
.PP
\fBExamples: \fP
.in +1c
\fB/usr/home/pgollucci/dev/compile/freebsd-6.1-stable/3.4.4/apreq/429956/r428290/5.8.8-2.2.3-prefork/include/apreq.h\fP.
.SS "\fBapr_size_t\fP \fBapreq_value_t::dlen\fP"
.PP
length of data 
.PP
\fBExamples: \fP
.in +1c
\fB/usr/home/pgollucci/dev/compile/freebsd-6.1-stable/3.4.4/apreq/429956/r428290/5.8.8-2.2.3-prefork/include/apreq.h\fP.
.SS "char* \fBapreq_value_t::name\fP"
.PP
value name 
.PP
\fBExamples: \fP
.in +1c
\fB/usr/home/pgollucci/dev/compile/freebsd-6.1-stable/3.4.4/apreq/429956/r428290/5.8.8-2.2.3-prefork/include/apreq.h\fP.
.SS "\fBapr_size_t\fP \fBapreq_value_t::nlen\fP"
.PP
length of name 
.PP
\fBExamples: \fP
.in +1c
\fB/usr/home/pgollucci/dev/compile/freebsd-6.1-stable/3.4.4/apreq/429956/r428290/5.8.8-2.2.3-prefork/include/apreq.h\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libapreq2 from the source code.
