#!/bin/bash -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

case "$1" in
  configure|upgrade)

  if [ -x "$(command -v MAKEDEV)" ]; then
    echo "creating fuse device node..."
    cd /dev; mknod -m 660 fuse c 10 229
  fi
  test -f /etc/default/fuse-utils && rm -f /etc/default/fuse-utils;
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
