.TH "mdadm-startall" "8" 
.SH "NAME" 
\fBmdadm-startall\fP \(em helper script to start all known arrays 
.SH "SYNOPSIS" 
.PP 
\fB\fBmdadm-startall\fP\fR 
.SH "DESCRIPTION" 
.PP 
The \fB\fBmdadm-startall\fP\fR script scans the system for 
arrays and writes a configuration file matching the current state. It then 
starts all arrays it found. If a configuration file already exists and 
defines arrays, it is used instead. 
 
 
.SH "SEE ALSO" 
.PP 
mdadm (8), mdadm.conf(5) 
.SH "AUTHOR" 
.PP 
This manual page was written by Eduard Bloch blade@debian.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Thu 02 Sep 2010, 15:14 
