.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" Copyright (C) 1996 Erick Branderhorst <branderh@debian.org>
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2, or (at your option) any later
.\" version.
.\" 
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\" 
.\" You should have received a copy of the GNU General Public License with
.\" your Debian GNU/Linux system, in /usr/share/doc/copyright/GPL, or with
the
.\" dpkg source package as the file COPYING.  If not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" This manpage is created thanks to:
.\" Kai Henningsen <kai@khms.westfalen.de>,
.\" Ian Jackson <iwj10@cus.cam.ac.uk>,
.\" David H. Silber <dhs@firefly.com> &
.\" Carl Streeter <streeter@cae.wisc.edu>.
.\" 
.\" Adapted for PAM by J.H.M. Dassen (Ray) <jdassen@wi.LeidenUniv.nl>
.\"
.TH PAM-UNDOCUMENTED 7 "October 1998" "Debian Project" "Debian GNU/Linux"
.SH NAME
pam-undocumented \- No manpage for this PAM-related program, utility or function.
.SH DESCRIPTION
This
.B program, utility
or 
.B function 
does not have a useful manpage.
There is however documentation available for it in the 
.B libpam-doc
package, which contains
.IR "The Linux-PAM System Administrator's Guide" ,
.IR "The Linux-Pam Application Developer's Guide" ", and"
.IR "The Linux-Pam Module Writer's Guide" .
If you are a competent and accurate writer and are willing to spend the time
reading the existing source code and documentation and to write good
manpages please write a better man page than this one. Please 
.B contact 
the 
.B package maintainer 
in order to avoid several people working on the same manpage.

If you still didn't find the information you are looking for you might
consider posting a call for help to
.IR debian-user@lists.debian.org .
.SH SEE ALSO
.BR info (1),
.BR whatis (1),
.BR apropos (1),
.BR dpkg (1),
.BR locate (1),
.BR find (1),
.BR updatedb (1),
.BR undocumented (2).
.SH AUTHOR
Erick Branderhorst <branderh@debian.org>.
.SH THANKS
Kai Henningsen,
Ian Jackson, 
David H. Silber, 
Carl Streeter,
Ray Dassen.

