.TH UNIX_CHKPWD 8 "4 Jun 1999" "Linux-PAM 0.69" "Linux-PAM Manual"
.SH NAME
\fBunix_chkpwd\fR \- check the password of the invoking user
.SH SYNOPSIS
<not invoked manually>
.SH DESCRIPTION
A helper binary for the pam_unix module, unix_chkpwd, is provided to check
the user's password when it is stored in a read protected database, such as
shadow'd passwords. This binary is very simple and will only check the password
of the user invoking it. It is called transparently on behalf of the user by
the authenticating component of the pam_unix module. In this way it is possible
for applications like
.B xlock
to work work without being setuid root. 
.SH USAGE
This program is not intended to be called directly by users and will log to syslog
if it is called improperly (i.e., by someone trying to exploit it).
