#! /bin/sh

set -e

dpkg --assert-support-predepends

if [ "$1" = "upgrade" -a -f /etc/init.d/sysklogd ]; then
    if [ -f /etc/init.d/sysklogd ]
    then
	set +e
	if [ -x /usr/sbin/invoke-rc.d ]
	then
	    invoke-rc.d sysklogd stop
	else
	    sh /etc/init.d/sysklogd stop
	fi
	set -e
    fi
fi

exit 0
