# $Id: Makefile,v 1.1.1.1 2006-08-28 17:52:12 bzhang Exp $
# Makefile for the linux Sparc-specific parts of the memory manager.
#

EXTRA_AFLAGS := -ansi

obj-y    := padre_cache.o fault.o init.o extable.o

