.TH "todo" 3 "6 Mar 2009" "Version 2.12" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBGlobal \fBAPREQ_COOKIE_MAX_LENGTH\fP \fP" 1c
convert this macro to an \fBapreq_module_t\fP method.
.PP
.PP
.PP
 
.IP "\fBGlobal \fBapreq_atoi64f\fP \fP" 1c
What happens when s is malformed? Should this return an unsigned value instead? 
.PP
.PP
 
.IP "\fBGlobal \fBapreq_atoi64t\fP \fP" 1c
What happens when s is malformed? Should this return an unsigned value instead? 
.PP
.PP
 
.IP "\fBGlobal \fBapreq_brigade_concat\fP \fP" 1c
Flesh out these error codes, making them as explicit as possible. 
.PP

