# $Id: Makefile,v 1.1.1.1 2010-09-22 00:23:49 jmaggard Exp $
# Makefile for the linux Sparc-specific parts of the memory manager.
#

EXTRA_AFLAGS := -ansi

obj-y := padre_ecounter.o
obj-$(CONFIG_PADRE_SERIAL) += padre_serial.o

