#!/bin/sh

#
# md5_image_maker: Produce raw images of partitions and store their appropriate
# md5 sums in a separate file.
# Written by Yotam Rubin <yotam@makif.omer.k12.il>
# Usage: md5_image_maker <partition> <partition> ...
#

MD5SUM=/usr/bin/md5sum

if [ -z $1 ]; then
    echo "Usage: $0 <partition> <partition> ..."
    exit 0
fi

touch md5sums

for partition in $@; do
    dd if=/dev/$partition of=$partition.bin
    $MD5SUM $partition.bin  >> md5sums
done

