.\"                             -*- Mode: Nroff -*- 
.\" lcf.1 --- 
.\" Author           : Manoj Srivastava ( srivasta@green-gryphon.com ) 
.\" Created On       : Fri Feb  1 11:17:32 2002
.\" Created On Node  : glaurung.green-gryphon.com
.\" Last Modified By : Manoj Srivastava
.\" Last Modified On : Mon May  2 01:09:42 2005
.\" Last Machine Used: glaurung.internal.golden-gryphon.com
.\" Update Count     : 28
.\" Status           : Unknown, Use with caution!
.\" HISTORY          : 
.\" Description      : 
.\" 
.\" Copyright (c) 2002 Manoj Srivastava <srivasta@debian.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
.\" 02111-1307, USA.
.\"
.\" $Id: lcf.1,v 1.1 2002/02/26 20:12:06 srivasta Exp $
.TH LCF 1 "Feb 1 2002" "Debian" "Debian GNU/Linux manual"
.SH NAME
lcf \- Determine which of the historical versions of a config is installed
.SH SYNOPSIS
.B lcf
.I [options]
.I <Destination File Name>
.I <Historical MD5SUM source directory>
.SH DESCRIPTION
This script, given a destination file name, and a directory containing
md5sums of historical versions of the file, attempts to determine if
the installed version corresponds to a historical version. lcf uses
the same algorithm that ucf uses, and should exhibit the same
behaviour. 
.PP
The source directory is the place where historical md5sums are
expected to live. Specifically, the historical md5sums are looked for
in either the file 
.I ${filename}.md5sum, 
or the subdirectory
.I ${filename}.md5sum.d/
.SH OPTIONS
.TP
.B "-h, --help"
Print a short usage message
.TP
.B "-n, --no-action"
Dry run. Print the actions that would be taken if the script is
invoked, but take no action.
.TP
.B "-d [n], --debug [n]"
Set the debug level to the (optional) level
.I n 
(n defaults to 1). This turns on copious debugging information.
.TP
.B "-v,  --verbose"
Make the script be very verbose about setting internal variables.
.SH FILES
.PP
.I /var/lib/ucf/hashfile,
.I /etc/ucf.conf
.SH "SEE ALSO"
ucf(1)
ucf.conf(5).
.SH BUGS
There are no bugs.  Any resemblance thereof is delirium. Really.
.SH AUTHOR
This manual page was written Manoj Srivastava <srivasta@debian.org>,
for the Debian GNU/Linux system.
