386_OBJECTS= \
    $(_OBJ_DIR)\i386\resource.res \
    $(_OBJ_DIR)\i386\tapdrvr.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\resource.res \
    $(_OBJ_DIR)\ia64\tapdrvr.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\resource.res \
    $(_OBJ_DIR)\amd64\tapdrvr.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\resource.res \
    $(_OBJ_DIR)\arm\tapdrvr.obj

PASS0_ARM_OBJECTS=

