#!/bin/sh

mkdir ${ADTTMP}/locale
localedef -c -i en_US -f UTF-8 ${ADTTMP}/locale/en_US.utf8

LOCPATH=${ADTTMP}/locale \
    HOME=${ADTTMP} \
    LANG=en_US.utf8 \
    LC_ALL=en_US.utf8 \
    xvfb-run -a dbus-run-session make -C tests check VERBOSE=1
