#!/bin/sh

if [ "$2" = "up" ]; then
  if ! /sbin/ifup $1; then
    ifconfig $1 192.168.168.168
    run-parts /etc/network/if-up.d
  fi
elif [ "$2" = "down" ]; then
  /sbin/ifconfig $1 0.0.0.0
fi

exit 1
