.TH DOMAINNAME 1 "Jul 19, 1997" "" "Linux User's Manual"
.SH NAME
domainname \- set the NIS domainname of the system
.SH SYNOPSIS
.B domainname
.RB [ domain ]
.SH DESCRIPTION
.B Domainname
sets or displays the current NIS domainname of the system.
.SH ARGUMENTS
.IP \fBdomain\fP
New NIS domain for the system
.PP
If no argument is given, \fBdomainname\fP prints out the current
NIS domain.
.SH AUTHOR
Miquel van Smoorenburg (miquels@cistron.nl)
.SH "SEE ALSO"
.BR ypbind (1),
.BR ypwhich (1)
