.TH startpar-upstart-inject 8 2012-06-05 
.SH NAME
startpar-upstart-inject \- notify startpar of started/stopped upstart jobs
.
.SH SYNOPSIS
.B startpar-upstart-inject
.I job-name
.I instance
.I [started|stopped]
.
.SH DESCRIPTION
.B startpar-upstart-inject
is a helper command for notifying
.B startpar
whenever an upstart job has started or stopped.  It allows
.B startpar
to run in a manner compatible with upstart\-based systems, where
many/most jobs are started directly by upstart and not by
.BR startpar .
In this scenario,
.B startpar
must be notified whenever an upstart job has started so that it can run
the init scripts for services that declare a dependency on that job.
.
.SH OPTIONS
The
.B startpar-upstart-inject
command takes three arguments, all of which are mandatory.
.TP
.I job-name
The name of the
.B upstart
job.  Normally this will match the name of a script in the
.I /etc/init.d
directory.
.
.TP
.I instance
The instance of the
.B upstart
job, if any; otherwise, an empty string.  This is currently ignored by
.BR startpar ,
which has no concept of service instances.
.
.TP
.I [started|stopped]
The single word
.I started
or
.I stopped
which indicates whether the listed job has been started or stopped.
.
.SH FILES
.TP
.I /etc/init/startpar-bridge.conf
upstart job which invokes
.B startpar-upstart-inject
each time another upstart job starts
.
.SH SEE ALSO
.BR init (8)
.BR insserv (8)
.BR startpar (8)
.BR upstart-events (7)
.
.SH AUTHOR
Written by Steve Langasek <steve.langasek@canonical.com>
.
.SH COPYRIGHT
Copyright \(co 2012 Canonical Ltd.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
