#!/bin/sh -e

if [ "$1" = configure ]; then
	install-info --quiet --section "General Commands" "General Commands" \
		/usr/share/info/tar.info.gz

	update-alternatives --install /usr/sbin/rmt rmt /usr/sbin/rmt-tar 50 \
                    --slave /usr/share/man/man8/rmt.8.gz rmt.8.gz \
                            /usr/share/man/man8/rmt-tar.8.gz
fi

#DEBHELPER#
