#!/bin/sh -e

if [ "$1" = remove ]; then 
	install-info --quiet --remove tar
	if test -L /sbin/rmt && test /sbin/rmt -ef /usr/sbin/rmt; then
		rm -f /sbin/rmt
	fi
	update-alternatives --remove rmt /usr/sbin/rmt-tar
fi

#DEBHELPER#
