.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LVM-BIN-SCAN 8 "December 26, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lvm-bin-scan \- program to maintain symlinks in /sbin for
.B lvmiopversion (8)
.SH SYNOPSIS
.B lvm-bin-scan
.br
.B lvm-bin-scan -x
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBlvm-bin-scan\fP is a simple script which will look for LVM binary
sets in /sbin/lvm-{version}, and ensure that there exist symlinks
in /sbin to lvmiopversion for each tool provided, and conversely
to remove such symlinks when no such tool exists.
.PP
It is intended to be run from package maintenance scripts, in particular
the \fIpostinst\fP and \fIpostrm\fP scripts, as follows:
.PP
\fB[ "x$1" = "xconfigure" -a -x /usr/sbin/lvm-bin-scan ] && /usr/sbin/lvm-bin-scan\fP
.SH OPTIONS
There is only one option; \fBlvm-bin-scan -x\fP will remove \fIall\fP symlinks to
\fBlvmiopversion\fP from /sbin; it is intended to be used from the \fIprerm\fP
script for \fBlvm-common\fP.
.SH AUTHOR
This manual page was written by Tom Lees <tom@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
.BR lvmiopversion (8),
.BR lvm (8).
