.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LVMIOPVERSION 8 "December 26, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lvmiopversion \- program to report LVM protocol version
.SH SYNOPSIS
.B lvmiopversion
.br
.B lvmtoolname
.RI [ options ] ...
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
When invoked as \fBlvmiopversion\fP, the program reports the LVM
protocol version of the currently running kernel. However,
when invoked otherwise (eg as \fB{program}\fP), it acts as a wrapper,
and it will execute the program \fB/sbin/lvm-{version}/{program}\fP
where \fB{version}\fP is the protocol version. For
example, if it were called as
\fBvgscan -a\fP, it might execute \fB/sbin/lvm-10/vgscan -a\fP.
.PP
If it cannot determine the protocol version when invoked as a wrapper
(which may be because it does not have root permissions), it will
execute \fB/sbin/lvm-default/{program}\fP; \fB/sbin/lvm-default\fP
should be a symlink, and under Debian this is set up via the alternatives mechanism.
.SH OPTIONS
The program itself does not take any options; however, when invoked as
a wrapper, the programs it executes in turn may take options.
.SH AUTHOR
This manual page was written by Tom Lees <tom@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
.BR lvm (8),
.BR update-alternatives (8).
