.TH ils2mac 1 
.ad
.fi
.SH NAME
ils2mac
\-
Convert ils output to mactime parsable data
.SH SYNOPSIS
.na
.nf
\fBils2mac\fR 
.SH DESCRIPTION
Take a stream of time machine formatted data from ils and re-arrange
the fields into the fixed order that mactime expects.

This program should not be necessary. The next version of mactime should
understand time machine format instead of just pretending it does. 

Kludge: if the first line is not in time machine format assume that
we are looking at output from the grave-robber which prepends a date
line of its own (which is gross because time machine data already
contains a time stamp, and the obvious fix is to fix grave-robber).
.ad
