#! /bin/sh

case "$1" in
	remove)
		;;
	purge)
		echo "Purging grave-robber databases..."
		rm -rf /var/cache/tct /etc/tct
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

