#!/bin/sh

set -e

case "$1" in
	remove|upgrade|remove-in-favour|deconfigure-in-favour)
		[ -L /usr/doc/tct ] && rm -f /usr/doc/tct
		[ -f /usr/sbin/tct  ] && rm -f /usr/sbin/tct
		;;
	failed-upgrade)
		;;
esac

exit 0
