#!/bin/sh
set -e
if [ configure = "$1" ]; then
	# cleanup diversions from wheezy
	if dpkg --compare-versions "$2" lt "1.1-3" ; then
		dpkg-divert --package libunwind-setjmp0 --remove --rename --divert /usr/lib/libunwind-setjmp.so.0.0.0.old /usr/lib/libunwind-setjmp.so.0.0.0
		dpkg-divert --package libunwind-setjmp0 --remove --rename --divert /usr/lib/libunwind-setjmp.so.0.old /usr/lib/libunwind-setjmp.so.0
	fi
fi
#DEBHELPER#
