.\"                             -*- Mode: Nroff -*- 
.\" updateConfFile.1 --- 
.\" Author           : Manoj Srivastava ( srivasta@green-gryphon.com ) 
.\" Created On       : Fri Feb  1 11:17:32 2002
.\" Created On Node  : glaurung.green-gryphon.com
.\" Last Modified By : Manoj Srivastava
.\" Last Modified On : Mon Apr 19 12:16:51 2004
.\" Last Machine Used: glaurung.internal.golden-gryphon.com
.\" Update Count     : 28
.\" Status           : Unknown, Use with caution!
.\" HISTORY          : 
.\" Description      : 
.\" Copyright (c) 2002 Manoj Srivastava <srivasta@debian.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
.\" 02111-1307, USA. 
.\"
.\" $Id: ucf.conf.5,v 1.2 2002/02/25 18:07:21 srivasta Exp $
.\"
.TH UCF.CONF 5 "Feb 12 2002" "Debian" "Debian GNU/Linux manual" 
.SH NAME
ucf.conf \- site\-wide configuration file for
.B ucf
.SH SYNOPSIS
.I /etc/ucf.conf
.SH "DESCRIPTION"
The file 
.I /etc/ucf.conf
is actually a 
.BR "Bourne Shell"
snippet included during the package build process, and hence you may
put any shell directive in that file (just make very sure you know
what you are doing).
.PP
All the variables have reasonable default values, and some may be
overridden on a per run or a per individual basis by using
environment variables, and all configurable variables can be
overridden by options to the scripts themselves.
.PP
The value of a variable can be set so:
.TP 3
a)
Defaults exist in the rules file. These are the values used if no
customization is done.
.IP b)
Some variables can be set in the config file 
.I /etc/ucf.conf. 
These values override the defaults.
.IP c)
Some variables can also be set by setting a corresponding environment
variable.  These values override the config file and the defaults.
.IP d)
Using script command line 
options. All configurable variables may be set by this method, and
will override the other methods above.
.SH "Configuration File options"
At the moment, the user modifiable variables supported are:
.TP 18
.B DEBUG
Debugging information: The default value is 0 (no debugging
information is printed). To enable debugging output, set the value to
1. 
.TP
.B VERBOSE
Verbosity: The default value is 0 (quiet). To change the default
behavior, set the value to 1.
.TP
.B conf_force_conffold
Force the installed file to be retained. The default is to have this
variable unset, which makes the script ask in case of doubt.  This can
be overridden by the environment variable
.B UCF_FORCE_CONFFOLD
.TP
.B conf_force_conffnew
Force the installed file to be overridden. The default is to have this
variable unset, which makes the script ask in case of doubt.  This can
be overridden by the environment variable
.B UCF_FORCE_CONFFNEW
.TP
.B conf_source_dir
This is the directory where the historical md5sums for a file are
looked for.  Specifically, the historical md5sums are looked for in
either the file
.I ${filename}.md5sum,
or the subdirectory 
.I ${filename}.md5sum.d/ 
.TP
.B conf_old_mdsum_file
Force the historical md5sums to be read from this file, rather than
defaulting to living in the source directory.  Setting this option
overrides settings in the environment variable
.B UCF_OLD_MDSUM_FILE
.SH Files
System\-wide defaults are placed in 
.I /etc/ucf.conf,
.SH "SEE ALSO"
.BR ucf (1),
.SH BUGS
There are no bugs.  Any resemblance thereof is delirium. Really.
.SH AUTHOR
This manual page was written by Manoj Srivastava <srivasta@debian.org>,
for the Debian GNU/Linux system.

