#!/bin/sh
set -e

CONFFILE=/etc/apache2/mods-available/perl.conf
CONFLINK=/etc/apache2/mods-enabled/perl.conf
if [ -n "$2" ] && [ -e "$CONFFILE" ] \
   && dpkg --compare-versions "$2" lt 2.0.2-2.4
then
	sed -i -e'/^[[:space:]]*PerlModule[[:space:]]\+Apache2[[:space:]]*/d' \
		$CONFFILE
	if [ ! -s "$CONFFILE" ]; then
		rm $CONFFILE
		if [ -L "$CONFLINK" ]; then
			rm $CONFLINK
		fi
	fi
fi

#DEBHELPER#
