.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Adduser and this manpage are copyright 1995 by Ted Hajek
.\"
.\" This is free software; see the GNU General Public Lisence version 2
.\" or later for copying conditions.  There is NO warranty.
.TH "deluser.conf" 5 "Version VERSION" "Debian GNU/Linux"
.SH NAME
/etc/deluser.conf \- configuration file for 
.B deluser(8) 
and 
.BR delgroup(8) .
.SH DESCRIPTION
The file 
.I /etc/deluser.conf
contains defaults for the programs
.B deluser(8) 
and 
.BR delgroup(8) .
Each option takes the form
.IR option " = " value .
Double or single quotes are allowed around the value.  Comment lines
must have a pound sign (#) in the first line.

The valid configuration options are:
.TP
\fBREMOVE_HOME\fP
Removes the home directory and mail spool of the user to be removed.
Value may be 0 or 1.
.TP
\fBREMOVE_ALL_FILES\fP
Removes all files on the system owned by the user to be removed.
If this option is activated
.B REMOVE_HOME
as no effect. Values may be 0 or 1.
.TP
\fBBACKUP\fP
If
.B REMOVE_HOME
or
.B REMOVE_ALL_FILES
is activated all files are backuped before they are removed. The backup
file that is created is username.tar(.gz|.bz2) in the current working
directory. The compression method is choosed to the best that is availible.
Values may be 0 or 1.
.SH FILES
.I /etc/deluser.conf
.SH SEE ALSO
deluser(8)


