#!/bin/sh
case "$1" in
	deconfig)
		ifconfig $interface | grep -q UP
		if [ $? -gt 0 ]; then
		  /sbin/ifconfig $interface 0.0.0.0
 		fi
		;;

	renew|bound)
		[ -n "$ip" ] && echo "IP=$ip"
		[ -n "$broadcast" ] && echo "BROADCAST=$broadcast"
		[ -n "$netmask" ] && echo "NETMASK=$netmask"
		[ -n "$router" ] && echo "ROUTERS=$router"
		[ -n "$domain" ] && echo "DOMAIN=$domain"
		[ -n "$dns" ] && echo "DNS=$dns"
		;;
	*)
		;;
esac
exit 0
