#!/bin/sh -e
# $Id: krb5-rsh-server.postinst,v 1.1 2000/10/26 01:31:46 hartmans Exp $

if [ "$1" = configure ] && [ -z "$2" ]; then
        update-inetd --group Kerberos --add 'kshell\t\tstream\ttcp\tnowait\troot\t/usr/sbin/tcpd\t/usr/sbin/kshd -5ec'
        update-inetd --group Kerberos --add 'eklogin\t\tstream\ttcp\tnowait\troot\t/usr/sbin/tcpd\t/usr/sbin/klogind -5ec'
else
        update-inetd --enable kshell,eklogin
fi

#DEBHELPER#
