#! /bin/sh

set -e

. /usr/share/debconf/confmodule

kver=`uname -r|cut -d. -f 1,2`

# Note that raidtools2 requires patching on older kernels

if [ $kver = '2.0' -o $kver = '2.1' -o $kver = '2.2' ]; then

  if ! grep -q '^unused devices:' /proc/mdstat &> /dev/null
  then
  
    db_input high raidtools2/nosupport || true
    db_go
  
    db_get raidtools2/nosupport
  
    if [ ! "$RET" = "true" ]; then
  
      STOP=1
  
    fi
  
  fi

fi

# If the user has chosen not to install raidtools2, don't do the rest

if [ ! "$STOP" = 1 ]; then

  if [ -f /etc/mdtab ]; then

    # Make a note about old RAID arrays

    db_input high raidtools2/oldraid || true
    db_go

  fi

  # Note about the raid2 init script

  if [ -f /etc/rcS.d/S25raid2 ]; then

    db_input low raidtools2/init || true
    db_go

  fi

fi
