.\" -*- nroff -*-
.TH mdrun 8
.SH NAME
ckraid,  mdadd,  mdrun,  mdstop,  mdop \- obsolete

.SH DESCRIPTION

In earlier RAID versions, \fBckraid\fR, \fBmdadd\fR, \fBmdrun\fR,
\fBmdstop\fR and \fBmdop\fR were commands for managing RAID devices.
This work is now done by \fBraidstart\fR, \fBraidstop\fR, \fBraid0run\fR
and the kernel.

If kernel autostart is disabled, the \fBraidstart\fR command can be
used to start persistant devices. Non-persistant linear/RAID0 devices
should be started with \fBraid0run\fR. Stopping the arrays at shutdown
isn't mandatory.

Fixing arrays is now handled automaticly by the kernel, in the background.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8),
.IR mkraid (8)
