.\" -*- nroff -*-
.TH raidhotgenerateerror 8
.SH NAME
raidhotgenerateerror - mark a disk faulty and remove it from a RAID array

.SH SYNOPSIS
.B raidhotgenerateerror
[--all] [--configfile] [--help] [--version] [-achv] [\fIRAID-ARRAY\fR] [\fITARGET-DISK\fR]
.B raidsetfaulty
[--all] [--configfile] [--help] [--version] [-achv] [\fIRAID-ARRAY\fR] [\fITARGET-DISK\fR]

.SH DESCRIPTION

\fBraidsetfaulty\fR and \fBraidhotgenerateerror\fR mark an active disk
faulty and thus remove it from the RAID array. This is of course dangerous:
no array should stay in a 'faulty' state for a long time, a disk failure in
that period of time is not recoverable and data might be lost.
Nevertheless this utility is a useful extension of administration and
hot-plug utilities.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8),
.IR mkraid (8)
