.\" -*- nroff -*-
.TH raidhotadd 8
.SH NAME
raidhotadd, raidhotremove - add and remove disks from arrays

.SH SYNOPSIS
.B raidhotadd
[--all] [--configfile] [--help] [--version] [-achv] [\fIRAID-ARRAY\fR] [\fITARGET-DISK\fR]

.B raidhotremove
[--all] [--configfile] [--help] [--version] [-achv] [\fIRAID-ARRAY\fR] [\fITARGET-DISK\fR]

.SH DESCRIPTION

\fBraidhotadd\fR and \fBraidhotremove\fR can be used to add and remove
disks from RAID-1, -4 and -5 arrays, while they are active.

.SH SEE ALSO
.IR raidtab (5),
.IR raidstart (8),
.IR mkraid (8)
