usr/include
usr/lib/libgc*.so
usr/lib/libgc*.a
usr/lib/libgc*.la
usr/share/man/man3
usr/share/doc/gc/*.html usr/share/doc/libgc1c2
usr/share/doc/gc/barrett_diagram usr/share/doc/libgc1c2
usr/share/doc/gc/README usr/share/doc/libgc1c2
usr/share/doc/gc/README.contributors usr/share/doc/libgc1c2
usr/share/doc/gc/README.cords usr/share/doc/libgc1c2
usr/share/doc/gc/README.linux usr/share/doc/libgc1c2
