'\" t
.\"     Title: get_pcaps
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/23/2011
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"  Language: English
.\"
.TH "GET_PCAPS" "1" "09/23/2011" "GET_PCAPS" "GET_PCAPS"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
get_pcaps \- List Process Capabilities
.SH "SYNOPSIS"
.HP 5
\fBget_pcaps\fR <pid> [<pid> ...]
.SH "DESCRIPTION"
.PP
\fBget_pcaps\fR
is a simple utility to display the capabilities on the queried process(es)\&.
The capabilities are displayed in the cap_from_text(3) format\&.
.SH "FILES"
.PP
None
.SH "SEE ALSO"
.PP
\fBcap_from_text\fR(3),
.SH "COPYRIGHT"
Copyright \(co 1997-8,2007 Andrew G. Morgan  <morgan@kernel.org>
.br
