#! /usr/bin/perl -w

$| = 1;

print "Reading configuration... ";
open CONF, "<debian/build/config.status" or 
	die "Can't open debian/build/config.status: $!";
@CONF = <CONF>;
close CONF;
print "done\n";

print "Checking if sasl2 was found... ";
if (not grep /SASL_LIBS.*-lsasl2/, @CONF) {
	print "no\n";
	die "SASL2 support not enabled";
}
print "okay\n";
