.TH exim_lock 1 "Jan 31, 2002" "Debian GNU/Linux" "Exim"
.SH NAME
exim_lock \- A program to lock a file exactly as Exim would
.SH SYNOPSIS
.B exim_lock
.I [-v] [-q] [-lockfile] [-fcntl|-mbx] filename [command]
.SH "DESCRIPTION"
.B exim_lock
is a program to lock a file in exactly the same way as Exim would. It is
intended for the investigation of interlocking problems, but can also be
used to prevent Exim from modifying the file while you do something else
to it (for example if you need to manually edit your mailbox in /var/mail).
.PP
Apart from specifying the name of the file to lock, which is required, the
following optional arguments may also be supplied to
.B exim_lock
:
.TP
.B -v
specifies verbose mode (this is overridden if
.B -q
is also specified);
.TP
.B -q
specifies quiet mode (takes precendence over
.B -v
);
.TP
.B -fcntl
specifies that exim_lock should use an fcntl lock;
.TP
.B -lockfile
specifies that exim_lock should use a lock file (sometimes called a
"dotlock");
.TP
.B -mbx
specifies that exim_lock should lock using MBX rules. To quote from the
source of
.B exim_lock
, "This is complicated and is documented with the source of the c-client
library that goes with Pine and IMAP. What has to be done to interwork
correctly is to take out a shared lock on the mailbox, and an exclusive
lock on a /tmp file."
.br
.TP
.B command
specifies the command to run once the specified file is locked. The mailbox
will
be unlocked again when this command exits.
.PP
Note that if these parameters are not specified, then
.B exim_lock
will lock the file using fcntl and lockfile methods, and then run a shell.
.SH "SEE ALSO"
.BR exim (8)
.PP
There is also extensive documentation available in
.I /usr/doc/exim
and in the
.B info
system (try "info exim").

Please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
Exim was, and mostly is, written by Philip Hazel, inspired by Smail\ 3.
.PP
This manual page was written by Nick Phillips <nwp@lemon-computing.com>
for the Debian GNU/Linux system.
