.TH exim_dbmbuild 8
.SH NAME
exim_dbmbuild \- program to build a database file for exim
.SH SYNOPSIS
.B exim_dbmbuild
.I inputfile basename
.SH "DESCRIPTION"
The exim_dbmbuild program reads an input file in the format of an alias
file (see chapter 20) and writes a DBM database using the lower-cased alias
names as keys and the remainder of the information as data. Two arguments
are required: the name of the input file (which can be a single hyphen to
indicate the standard input), and the base name of the output database. For
example:

  exim_dbmbuild /etc/aliases /etc/aliases

reads the system alias file and creates a DBM database using /etc/aliases
as the base name. In systems that use the ndbm routines, the database
consists of two files called (in this case) /etc/aliases.dir and
/etc/aliases.pag, while in systems using the ndbm interface to the db
routines a single file called /etc/aliases.db is used. If the native db
interface is in use (USE_DB is set in a compile-time configuration file)
then a single file with no added prefix is used. In this case the two file
names on the command line must be different. The utility in fact creates
the database under a temporary name, and then renames the file(s).
.SH "SEE ALSO"
There is extensive documentation available in
.I /usr/share/doc/exim
and in the info system regarding exim.
Please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
This manual page was stitched together by Christoph Lameter <clameter@debian.org>
from the original documentation coming with the sourcepackage
for the Debian GNU/Linux system.
