.TH exinext 8
.SH NAME
exinext \- program to extract information from exim retry database
.SH SYNOPSIS
.B exinext
.I domain
.SH "DESCRIPTION"
A utility called exinext (mostly a perl script) provides the ability to
fish specific information out of the retry database. Given a mail domain
(or a complete address), it looks up the hosts for that domain, and outputs
any retry information. At present, the retry information is obtained by
running exim_dumpdb (see below) and post-processing the output. For
example:
.PP
.nf
  exinext piglet@milne.fict.book
  kanga.milne.fict.book:100.100.8.1 error 146: Connection refused
    first failed: 21-Feb-1996 14:57:34
    last tried:   21-Feb-1996 14:57:34
    next try at:  21-Feb-1996 15:02:34
  roo.milne.fict.book:100.100.8.3 error 146: Connection refused
    first failed: 20-Jan-1996 13:12:08
    last tried:   21-Feb-1996 11:42:03
    next try at:  21-Feb-1996 19:42:03
    past final cutoff time
.fi
.PP
You can also give exinext a local local_part, without a domain, and it will
give any retry information for it. Exinext is not particularly efficient,
but then it isn't expected to be run very often.
.SH "SEE ALSO"
There is extensive documentation available in
.I /usr/share/doc/exim
and in the info system regarding exim.
Please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
This manual page was stitched together by Christoph Lameter <clameter@debian.org>
from the original documentation coming with the sourcepackage
for the Debian GNU/Linux system.
