.TH exiqsumm 8
.SH NAME
exiqsumm \- script to summarise contents of mail queue
.SH SYNOPSIS
\fB mailq | exiqsumm \fR[\fB-a\fR] [\fB-c\fR]
.SH DESCRIPTION
The perl script called exiqsumm summarises a mail queue, by grouping
together all entries that are addressed to the same domain, and listing the
number of messages, number of bytes, and the oldest and newest messages in a
domain.
.PP
.nf
Count  Volume  Oldest  Newest  Domain
-----  ------  ------  ------  ------

    4    5222     16d      5d  cam.ac.uk
.fi
.PP
By default, the output is sorted by domain name; with the -a option it is
sorted by the age of the oldest message for that domain, with the -c option
it is sorted by the count of messages queued for that domain.
.SH "SEE ALSO"
There is extensive documentation available in
.I /usr/share/doc/exim
and in the info system regarding exim.
Please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
This manual page was stiched together by Mark Baker <mbaker@iee.org> from a
quick look at the code for the script.

The script was written by Christoph Lameter.
