.TH exiwhat 8
.SH NAME
exiwhat \- programs to query what running exim processes are doing 
.SH SYNOPSIS
.B exiwhat
.SH DESCRIPTION
The shell script called exiwhat first of all empties the processlog file in
Exim's log directory. It then uses the ps command to find all processes
running exim, and sends each one the SIGUSR1 signal. This causes each
process to write a single line describing its current activity to the
processlog file. The script waits a bit, then copies the file to the
standard output.
.PP
.nf
  164 0.53 daemon: -q1h, listening on port 25
10483 0.54 running queue: waiting for 0tAycK-0002ij-00 (10492)
10492 0.54 delivering 0tAycK-0002ij-00 to mail.ref.book [42.42.42.42]
  (editor@ref.book)
10592 0.53 handling incoming call from [245.211.243.242]
10628 0.54 accepting a local non-SMTP message
.fi
.PP
The first number in the output line is the process number; the second is
the Exim version number. The third line has been split here, in order to
fit it on the page. Because Exim processes run under a variety of uids, it
is necessary to run exiwhat as root in order to be able to send the signal
to all Exim processes.
.SH "SEE ALSO"
There is extensive documentation available in
.I /usr/share/doc/exim
and in the info system regarding exim.
Please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
This manual page was stiched together by Christoph Lameter <clameter@debian.org>,
from the original documentation coming with the sourcecode package for the Debian GNU/Linux system.
