.TH newaliases 8
.SH NAME
newaliases \- update /etc/aliases database
.SH SYNOPSIS
.B newaliases
.SH DESCRIPTION
This is a simple shell script calling
.B /usr/lib/sendmail
with the
.B -bi
option. It is provided for compatibility with the sendmail program.
It is not actually necessary to notify exim of changes to /etc/aliases
at all.
.SH FILES
/etc/aliases
.SH SEE ALSO
There is extensive documentation available in
.I /usr/share/doc/exim
and in the info system regarding exim.
 Debian users please be sure to have the
.B exim-doc
package installed.
.SH AUTHOR
This manual page was written by Christoph Lameter <clameter@debian.org>,
for the Debian GNU/Linux system.
