#!/bin/sh -e

case "$1" in
    configure)

	# Create /usr/doc symlink
	if [ -d /usr/doc -a ! -e /usr/doc/eximon ]; then
	    ln -sf ../share/doc/eximon /usr/doc/eximon
	fi
	;;
	
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
esac
