#!/bin/sh -e

case "$1" in
	remove|upgrade|remove-in-favour|deconfigure-in-favour)

		# Remove /usr/doc symlink
		if [ -L /usr/doc/eximon ]; then
		    rm -f /usr/doc/eximon
		fi
		;;

        failed-upgrade)
		;;
esac

