#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=libdevmapper1.02

set -e

case "$1" in
  start)
	echo -n "Loading device-mapper support"
	modprobe dm-mod 2> /dev/null || true
	modprobe dm-mirror 2> /dev/null || true
	modprobe dm-snapshot 2> /dev/null || true
	echo "."
	;;
  stop|restart|force-reload)
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
