.TH IN.IDENTTESTD 8 "" libident "Library functions"
.UC 3

.SH NAME
in.identtestd \- a small daemon that can be used to test Ident servers

.SH SYNOPSIS
in.identtestd

.SH DESCRIPTION
.I in.identtestd
is a small daemon (to be started from inetd)
that does an ident lookup on you if you telnet into it. Can be used
to verify that your Ident server is working correctly.

The source code can be found in the debian \fIlibident\fR source package, as
\fBident-tester.c\fR.

.SH EXAMPLE
A typical entry in /etc/inetd.conf would be:
.PP
.nf
9999 stream tcp nowait root /usr/sbin/in.identtestd in.identtestd
.fi
.PP
With the above entry in place and active, execute "telnet hostname 99999"
from either this system, or another system. It should show something like:

.in +4
.nf
Trying hostname...
Connected to hostname.
Escape character is '^]'.
Welcome to the IDENT server tester, version 1.9

(Linked with libident 0.22 Debian)

Connecting to Ident server at 192.168.1.1...
Querying for lport 1109, fport 9999....
Reading response data...
Userid response is:
   Lport........ 1109
   Fport........ 9999
   Opsys........ UNIX
   Charset...... <not specified>
   Identifier... paul
Connection closed by foreign host.
.fi
.in -4

.SH AUTHOR
Peter Eriksson <pen@lysator.liu.se>
.br
Manpage written for debian by Paul Slootman <paul@debian.org>.
.LP
.SH SEE ALSO
.I ident\c
\&(3),
.I identd\c
\&(8),
.I tcpd\c
\&(8)
