.TH io_queue_run 2 2009-06-10 "Linux 2.4" "Linux AIO"
.SH NAME
io_queue_run \- Handle completed io requests
.SH SYNOPSIS
.nf
.B #include <errno.h>
.br
.sp
.B #include <libaio.h>
.br
.sp
.BI "int io_queue_run(io_context_t " ctx_id ");"
.sp
.fi
.SH DESCRIPTION
.B io_queue_run
Attempts to read all the events events from
the completion queue for the aio_context specified by \fIctx_id\fP.
.SH "RETURN VALUES"
May return
\fI0\fP if no events are available.
Will fail with -\fBENOSYS\fP if not implemented.
.SH ERRORS
.TP
.B EFAULT
.I iocbs
referenced data outside of the program's accessible address space.
.TP
.B EINVAL
.I ctx_id
refers to an unitialized aio context, the \fIiocb\fP pointed to by
.I iocbs 
contains an improperly initialized iocb.
.TP
.B ENOSYS 
Not implemented.
.SH "SEE ALSO"
.BR io (3),
.BR io_cancel (3),
.BR io_fsync (3),
.BR io_getevents (3),
.BR io_prep_fsync (3),
.BR io_prep_pread (3),
.BR io_prep_pwrite (3),
.BR io_queue_init (3),
.BR io_queue_release (3),
.BR io_queue_wait (3),
.BR io_set_callback (3),
.BR io_submit (3),
.BR errno (3).
