#! /bin/sh /usr/share/dpatch/dpatch-run
## 082_ab_num_requests.dpatch by Stefan Fritsch <sf@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: Upstream r940526, Debian bug #541158

@DPATCH@
--- a/support/ab.c
+++ b/support/ab.c
@@ -633,6 +633,10 @@ static void ssl_proceed_handshake(struct connection *c)
 
 static void write_request(struct connection * c)
 {
+    if (started >= requests) {
+        return;
+    }
+
     do {
         apr_time_t tnow;
         apr_size_t l = c->rwrite;
@@ -695,6 +699,7 @@ static void write_request(struct connection * c)
         new_pollfd.client_data = c;
         apr_pollset_add(readbits, &new_pollfd);
     }
+    started++;
 }
 
 /* --------------------------------------------------------- */
@@ -1244,7 +1249,6 @@ static void start_connect(struct connection * c)
 
     /* connected first time */
     c->state = STATE_CONNECTED;
-    started++;
 #ifdef USE_SSL
     if (c->ssl) {
         ssl_proceed_handshake(c);
@@ -1773,7 +1777,6 @@ static void test(void)
                     }
                     else {
                         c->state = STATE_CONNECTED;
-                        started++;
 #ifdef USE_SSL
                         if (c->ssl)
                             ssl_proceed_handshake(c);
