.TH UPDATE\-PASSWD 8 "Narzêdzia Debiana" "DEBIAN"
.SH NAZWA
update\-passwd \- bezpiecznie aktualizuj /etc/passwd, /etc/shadow i /etc/group
.SH SK£ADNIA
.B update\-passwd
.RI [ opcje ]
.SH OPIS
.B update\-passwd
aktualizuje pliki /etc/passwd, /etc/shadow i /etc/group w dzia³aj±cych
systemach Debian.
Porównuje je z autorytatywnymi kopiami zawartymi w pakiecie
base\-passwd, a nastêpnie aktualizuje wszystkie wpisy w globalnym przedziale
systemowym (to jest 0\(en99).
.PP
.SH OPCJE
.B update\-passwd
wykorzystuje standardow± sk³adniê linii poleceñ GNU, gdzie d³ugie opcje
poprzedzone s± dwoma znakami my¶lnika (\(oq\-\(cq).
.TP
.BR \-p ,\  \-\-passwd\-master=PLIK
U¿yj PLIKu jako autorytatywnej kopii bazy danych "passwd".
Domy¶lna warto¶æ to
.IR /usr/share/base\-passwd/passwd.master .
.TP
.BR \-g ,\  \-\-group\-master=PLIK
U¿yj PLIKu jako autorytatywnej kopii bazy danych "group".
Domy¶lna warto¶æ to
.IR /usr/share/base\-passwd/group.master .
.TP
.BR \-P ,\  \-\-passwd=PLIK
U¿yj PLIKu jako systemowej bazy danych "passwd".
Domy¶lna warto¶æ to
.IR /etc/passwd .
.TP
.BR \-S ,\  \-\-shadow=PLIK
U¿yj PLIKu jako systemowej bazy danych "shadow".
Domy¶lna warto¶æ to
.IR /etc/shadow .
.TP
.BR \-G ,\  \-\-group=PLIK
U¿yj PLIKu jako systemowej bazy danych "group".
Domy¶lna warto¶æ to
.IR /etc/group .
.TP
.BR \-s ,\  \-\-sanity\-check
Wykonaj tylko testy poprawno¶ci, niczego nie zmieniaj.
.TP
.BR \-v ,\  \-\-verbose
Podawaj dok³adne informacje o wykonywanych czynno¶ciach.
.TP
.BR \-n ,\  \-\-dry\-run
Niczego nie zmieniaj, ale napisz co zosta³oby wykonane.
.TP
.BR \-L ,\  \-\-no\-locking
Nie blokuj bazy danych kont.
Opcji tej nale¿y u¿ywaæ tylko przy wy³apywaniu b³êdów,
nie w czasie normalnej pracy.
.B Powtarzam: u¿ywaj tej opcji tylko je¶li masz pewno¶æ, ¿e jej potrzebujesz!
.TP
.BR \-h ,\  \-\-help
Poka¿ instrukcjê u¿ycia
.BR update\-passwd .
.TP
.BR \-V ,\  \-\-version
Poka¿ wersjê.
.SH B£ÊDY
W tym momencie
.B update\-passwd
nie sprawdza pliku shadow.
Powinien sprawdzaæ czy wpisy w passwd s± tak¿e w shadow i na odwrót,
oraz czy tylko jeden z plików zawiera has³a.
.SH AUTOR
Wichert Akkerman <wakkerma@debian.org>
.PP
Ten program zosta³ napisany dla projektu Debian.
Prawa autorskie: Copyright 1999\(en2002 Wichert Akkerman i
copyright 2002, 2003 Colin Watson.
Jest rozpowszechniany pod wersj± 2 Powszechnej Publicznej Licencji GNU.
