# $Id: Makefile,v 1.1.1.1 2006-08-28 17:52:10 bzhang Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
