.TH DB_PRINTLOG 1 "May 3, 1998"
.SH NAME
db_printlog \- Debugging utility to dump Berkeley DB log files.
.SH SYNOPSIS
\fBdb_printlog\fP [\fB-N\fP] [\fB-h home\fP]
.SH DESCRIPTION
The
.I db_printlog
utility is a debugging utility that dumps Berkeley
DB log files in a human-readable format.
.PP
The options are as follows:
.TP 5
.B \-h
Specify a home directory for the database.
.TP 5
.B \-N
Do not acquire shared region locks while running. Other
problems such as potentially fatal errors in Berkeley DB will
be ignored as well. This option is intended only for debugging
errors and should not be used under any other circumstances.
.PP
The 
.I db_printlog 
utility attaches to one or more of the Berkeley DB
shared memory regions. In order to avoid region corruption, it should
always be given the chance to detach and exit gracefully. To cause
.I db_printlog 
to clean up after itself and exit, send it an interrupt signal (SIGINT).
.PP
The 
.I db_printlog 
utility exits 0 on success, and >0 if an error occurs.
.SH "ENVIRONMENT VARIABLES"
.TP 5
.B DB_HOME
If the -h option is not specified and the environment variable
.B DB_HOME 
is set, it is used as the path of the database home, as
described in 
.IR db_appinit (3).
.SH "SEE ALSO"
.IR db_archive (1),
.IR db_checkpoint (1),
.IR db_deadlock (1),
.IR db_dump (1),
.IR db_load (1),
.IR db_recover (1),
.IR db_stat (1),
