'\" t
.\"     Title: systemd.journal-fields
.\"    Author: Lennart Poettering <lennart@poettering.net>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/13/2015
.\"    Manual: systemd.journal-fields
.\"    Source: systemd
.\"  Language: English
.\"
.TH "SYSTEMD\&.JOURNAL\-F" "7" "01/13/2015" "systemd" "systemd.journal-fields"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.journal-fields \- Special journal fields
.SH "DESCRIPTION"
.PP
Entries in the journal resemble an environment block in their syntax, however with fields that can include binary data\&. Primarily, fields are formatted ASCII strings, and binary formatting is used only where formatting as ASCII makes little sense\&. New fields may be freely defined by applications, but a few fields have special meaning\&. All fields with special meaning are optional\&.
.SH "USER JOURNAL FIELDS"
.PP
User fields are fields that are directly passed from clients and stored in the journal\&.
.PP
MESSAGE=
.RS 4
The human readable message string for this entry\&. This is supposed to be the primary text shown to the user\&. It is usually not translated (but might be in some cases), and is not supposed to be parsed for meta data\&.
.RE
.PP
MESSAGE_ID=
.RS 4
A 128bit message identifier ID for recognizing certain message types, if this is desirable\&. This should contain a 128bit id formatted as lower\-case hexadecimal string, without any separating dashes or suchlike\&. This is recommended to be a UUID compatible ID, but this is not enforced, and formatted differently\&. Developers can generate a new ID for this purpose with
\fBjournalctl \-\-new\-id\fR\&.
.RE
.PP
PRIORITY=
.RS 4
A priority value between 0 (emerg) and 7 (debug) formatted as decimal string\&. This field is compatible with syslog\*(Aqs priority concept\&.
.RE
.PP
CODE_FILE=, CODE_LINE=, CODE_FUNC=
.RS 4
The code location generating this message, if known\&. Contains the source file name, the line number and the function name\&.
.RE
.PP
SYSLOG_FACILITY=, SYSLOG_IDENTIFIER=, SYSLOG_PID=
.RS 4
Syslog compatibility fields containing the facility (formatted as decimal string), the identifier string (i\&.e\&. "tag"), and the client PID\&.
.RE
.SH "TRUSTED JOURNAL FIELDS"
.PP
Fields prefixed with an underscore are trusted fields, i\&.e\&. fields that are implicitly added by the journal and cannot be altered by client code\&.
.PP
_PID=, _UID=, _GID=
.RS 4
The process, user and group ID of the process the journal entry originates from formatted as decimal string\&.
.RE
.PP
_COMM=, _EXE=, _CMDLINE=
.RS 4
The name, the executable path and the command line of the process the journal entry originates from\&.
.RE
.PP
_AUDIT_SESSION=, _AUDIT_LOGINUID=
.RS 4
The session and login UID of the process the journal entry originates from, as maintained by the kernel audit subsystem\&.
.RE
.PP
_SYSTEMD_CGROUP=, _SYSTEMD_SESSION=, _SYSTEMD_UNIT=, _SYSTEMD_OWNER_UID=
.RS 4
The contol group path in the systemd hierarchy, the systemd session ID (if any), the systemd unit name (if any) and the owner UID of the systemd session (if any) of the process the journal entry originates from\&.
.RE
.PP
_SELINUX_CONTEXT=
.RS 4
The SELinux security context of the process the journal entry originates from\&.
.RE
.PP
_SOURCE_REALTIME_TIMESTAMP=
.RS 4
The earliest trusted timestamp of the message, if any is known that is different from the reception time of the journal\&. This is the time in usec since the epoch UTC formatted as decimal string\&.
.RE
.PP
_BOOT_ID=
.RS 4
The kernel boot ID for the boot the message was generated in, formatted as 128bit hexadecimal string\&.
.RE
.PP
_MACHINE_ID=
.RS 4
The machine ID of the originating host, as available in
\fBmachine-id\fR(5)\&.
.RE
.PP
_HOSTNAME=
.RS 4
The name of the originating host\&.
.RE
.PP
_TRANSPORT=
.RS 4
How the entry was received by the journal service\&. One of
driver,
syslog,
journal,
stdout,
kernel
for internally generated messages, for those received via the local syslog socket with the syslog protocol, for those received via the native journal protocol, for the those read from a services\*(Aq standard output or error output, and for those read from the kernel, resp\&.
.RE
.SH "ADDRESS FIELDS"
.PP
During serialization into external formats the addresses of journal entries are serialized into fields prefixed with double underscores\&. Note that these aren\*(Aqt proper fields when stored in the journal, but addressing meta data of entries\&.
.PP
__CURSOR=
.RS 4
The cursor for the entry\&. A cursor is an opaque text string that uniquely describes the position of an entry in the journal and is portable across machines, platforms and journal files\&.
.RE
.PP
__REALTIME_TIMESTAMP=
.RS 4
The wallclock time (CLOCK_REALTIME) at the point in time the entry was received by the journal, in usec since the epoch UTC formatted as decimal string\&. This has different properties from
_SOURCE_REALTIME_TIMESTAMP=
as it is usually a bit later but more likely to be monotonic\&.
.RE
.PP
__MONOTONIC_TIMESTAMP=
.RS 4
The monotonic time (CLOCK_MONOTONIC) at the point in time the entry was received by the journal in usec formatted as decimal string\&. To be useful as an address for the entry this should be combined with with boot ID in
_BOOT_ID=\&.
.RE
.SH "SEE ALSO"
.PP

\fBsystemd\fR(1),
\fBjournalctl\fR(1),
\fBjournald.conf\fR(5)
.SH "AUTHOR"
.PP
\fBLennart Poettering\fR <\&lennart@poettering\&.net\&>
.RS 4
Developer
.RE
