debian/aa-update-browser /usr/sbin/
debian/vim-apparmor.yaml /usr/share/vim/registry/
usr/share/apparmor/apparmor.vim /usr/share/vim/addons/syntax/
etc/apparmor/logprof.conf
etc/apparmor/severity.db
usr/sbin/aa-autodep
usr/sbin/aa-complain
usr/sbin/aa-decode
usr/sbin/aa-genprof
usr/sbin/aa-audit
usr/sbin/aa-logprof
usr/sbin/aa-cleanprof
usr/sbin/aa-mergeprof
usr/sbin/aa-autodep
usr/sbin/aa-unconfined
usr/sbin/aa-enforce
usr/sbin/aa-disable
