.TH ncftpbookmarks 1 2003-07-09 "NcFTP Software"

.SH NAME
ncftpbookmarks \- full screen bookmarks editor for ncftp

.SH SYNOPSIS
ncftpbookmarks

.SH DESCRIPTION
.PP
.I ncftpbookmarks
is a full-screen bookmark editor for the
.I "File Transfer Protocol"
client
.IR "ncftp".
.PP
.I ncftp
can bookmark server name, login name and password
of your favorite ftp servers.
.I ncftpbookmarks
is used to handle these
bookmarks.

This full-screen editor can also be launched from the ncftp prompt with
the
.I bookmarks
command.

While using
.IR ncftpbookmarks ,
the screen is divided into two parts.
The left one gives a brief description of keyboard controls.
The right one lists all existing bookmarks.
Up and down arrows (or "u" and "d" keys) are used to move the cursor
in this list.
The "x" key is used to quit the editor.
Other commands have to be typed in full (e.g.\&
.IR /ed ,
.IR /del ).

.SH FILES
.IP $HOME/\.ncftp/bookmarks
Saves bookmark and host information.

.SH AUTHORS
.PP
Mike Gleason, NcFTP Software (mgleason@ncftp.com).

This man page was written by Nicolas Duboc (nicolas@duboc.net) for
the Debian distribution of the ncftp package.

.SH "SEE ALSO"
.PP
.IR ncftp (1)

